# Generated by Django 5.2 on 2025-04-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('ano_publicacao', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('capa', models.ImageField(upload_to='capa_livros/')),
                ('paginas', models.IntegerField()),
                ('editora', models.CharField(max_length=255)),
                ('idioma', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
